// Central registry for every VOS pSEO page.
// Drives: related-page strips, sitemap.xml, index.html hub cards.
// Order here is the order cards render on the pillar page.

module.exports = [
  {
    slug: 'order-entry-software',
    file: 'vos-order-entry-landing.html',
    label: 'Order Entry Software',
    card: 'Order Entry Software',
    blurb: 'Web-based order entry built for restaurants. Place supply orders 24/7 by voice or online. No hold time, no errors, no system to replace.',
    cluster: 'order',
  },
  {
    slug: 'order-taking-software',
    file: 'vos-order-taking-landing.html',
    label: 'Order Taking Software',
    card: 'Order Taking Software',
    blurb: 'Let customers place orders 24/7 by voice or web. Built for distributors and food service teams that take orders without the phone tag.',
    cluster: 'order',
  },
  {
    slug: 'order-fulfillment-software',
    file: 'vos-order-fulfillment-landing.html',
    label: 'Order Fulfillment Software',
    card: 'Order Fulfillment Software',
    blurb: 'Every order arrives clear and ready to pick. Voice, web, and app orders land in one queue so nothing waits on a voicemail.',
    cluster: 'order',
  },
  {
    slug: 'order-tracking-software',
    file: 'vos-order-tracking-landing.html',
    label: 'Order Tracking Software',
    card: 'Order Tracking Software',
    blurb: 'Know where every supply order stands, from submitted to delivered. Purchase order tracking for restaurants, sales order tracking for distributors.',
    cluster: 'order',
  },
  {
    slug: 'inventory-tracking-software',
    file: 'vos-inventory-tracking-landing.html',
    label: 'Inventory Tracking Software',
    card: 'Inventory Tracking Software',
    blurb: 'See real-time stock, get low-stock alerts, and reorder by voice or web. Simple inventory tracking that updates itself as you order.',
    cluster: 'inventory',
  },
  {
    slug: 'inventory-planning-software',
    file: 'vos-inventory-planning-landing.html',
    label: 'Inventory Planning Software',
    card: 'Inventory Planning Software',
    blurb: 'Plan next week off what you actually used, not a guess. Par levels per item and per location, built from your own order history.',
    cluster: 'inventory',
  },
  {
    slug: 'inventory-visibility-software',
    file: 'vos-inventory-visibility-landing.html',
    label: 'Inventory Visibility Software',
    card: 'Inventory Visibility Software',
    blurb: 'One live stock number your whole team can see. Every location, every role, no end-of-day spreadsheet to chase.',
    cluster: 'inventory',
  },
  {
    slug: 'inventory-control-software',
    file: 'vos-inventory-control-landing.html',
    label: 'Inventory Control Software',
    card: 'Inventory Control Software',
    blurb: 'Food inventory control that protects your margin. Stop over-ordering, catch delivery and invoice gaps, and see spend by category.',
    cluster: 'inventory',
  },
  {
    slug: 'catalog-management-software',
    file: 'vos-catalog-management-landing.html',
    label: 'Catalog Management Software',
    card: 'Catalog Management Software',
    blurb: 'Keep one product catalog current for your whole team. Per-account pricing, live availability, and voice ordering, all from a single catalog.',
    cluster: 'ops',
  },
  {
    slug: 'restaurant-stock-management-software',
    file: 'vos-restaurant-stock-management-landing.html',
    label: 'Restaurant Stock Management',
    card: 'Restaurant Stock Management Software',
    blurb: 'Stock counts that update as you order, from the walk-in to the phone in your pocket. Built for restaurant kitchens, not warehouses.',
    cluster: 'inventory',
  },
  {
    slug: 'restaurant-purchasing-software',
    file: 'vos-restaurant-purchasing-landing.html',
    label: 'Restaurant Purchasing Software',
    card: 'Restaurant Purchasing Software',
    blurb: 'Order from every distributor in one place. Purchase orders that write themselves and spend you can actually see.',
    cluster: 'ops',
  },
  {
    slug: 'restaurant-checklist-software',
    file: 'vos-restaurant-checklist-landing.html',
    label: 'Restaurant Checklist Software',
    card: 'Restaurant Checklist Software',
    blurb: 'Turn ordering into a repeatable checklist your team runs the same way every time, on every shift and at every location.',
    cluster: 'ops',
  },
];
