// Central registry for every VOS pSEO page.
// Drives: related-page strips, sitemap.xml, index.html hub cards.
// Order here is the order cards render on the pillar page.

module.exports = [
  {
    slug: 'order-entry-software',
    file: 'vos-order-entry-landing.html',
    label: 'Order Entry Software',
    card: 'Order Entry Software',
    blurb: "Voice order entry for restaurants. Say your supply order, check it, and send it any hour. Your food distributor sets up the account.",
    cluster: 'order',
  },
  {
    slug: 'order-taking-software',
    file: 'vos-order-taking-landing.html',
    label: 'Order Taking Software',
    card: 'Order Taking Software',
    blurb: "Give your restaurant customers a voice ordering app, open 24/7. Orders reach your team confirmed and in the format you already use.",
    cluster: 'order',
  },
  {
    slug: 'order-fulfillment-software',
    file: 'vos-order-fulfillment-landing.html',
    label: 'Order Fulfillment Software',
    card: 'Order Fulfillment Software',
    blurb: "Orders reach your pick line confirmed and complete. Customers order by voice around the clock, so nothing waits on a voicemail or a retype.",
    cluster: 'order',
  },
  {
    slug: 'order-tracking-software',
    file: 'vos-order-tracking-landing.html',
    label: 'Order Tracking Software',
    card: 'Order Tracking Software',
    blurb: "Know where every customer order stands without a call. Each order is confirmed, numbered and timestamped, with full history per account.",
    cluster: 'order',
  },
  {
    slug: 'distribution-resource-planning-software',
    file: 'vos-distribution-resource-planning-landing.html',
    label: 'Distribution Resource Planning',
    card: 'Distribution Resource Planning Software',
    blurb: "The order data your distribution planning runs on. Customer orders arrive 24/7 and structured, so tomorrow's volume is known before you plan.",
    cluster: 'order',
  },
  {
    slug: 'inventory-tracking-software',
    file: 'vos-inventory-tracking-landing.html',
    label: 'Inventory Tracking Software',
    card: 'Inventory Tracking Software',
    blurb: "See what is on hand as customer orders come in. Stock tied to order activity, and a catalog that updates as levels change.",
    cluster: 'inventory',
  },
  {
    slug: 'inventory-planning-software',
    file: 'vos-inventory-planning-landing.html',
    label: 'Inventory Planning Software',
    card: 'Inventory Planning Software',
    blurb: "Plan next week's buy from clean customer order data: dated history for every account, 24/7 order capture and a live stock view.",
    cluster: 'inventory',
  },
  {
    slug: 'inventory-replenishment-software',
    file: 'vos-inventory-replenishment-landing.html',
    label: 'Inventory Replenishment Software',
    card: 'Inventory Replenishment Software',
    blurb: "See what is running low as customer orders land, and restock before an account's order comes up short.",
    cluster: 'inventory',
  },
  {
    slug: 'inventory-automation-software',
    file: 'vos-inventory-automation-landing.html',
    label: 'Inventory Automation Software',
    card: 'Inventory Automation Software',
    blurb: "No re-keying: orders arrive in your format while stock and your catalog update on their own. Customers still confirm every order.",
    cluster: 'inventory',
  },
  {
    slug: 'inventory-visibility-software',
    file: 'vos-inventory-visibility-landing.html',
    label: 'Inventory Visibility Software',
    card: 'Inventory Visibility Software',
    blurb: "One stock picture for your reps, your warehouse and your customers, updated as orders come in. No morning stock sheet to chase.",
    cluster: 'inventory',
  },
  {
    slug: 'inventory-control-software',
    file: 'vos-inventory-control-landing.html',
    label: 'Inventory Control Software',
    card: 'Inventory Control Software',
    blurb: "Find where shorts, substitutions and order errors cost you margin, with checked orders and a catalog that keeps up with your stock.",
    cluster: 'inventory',
  },
  {
    slug: 'catalog-management-software',
    file: 'vos-catalog-management-landing.html',
    label: 'Catalog Management Software',
    card: 'Catalog Management Software',
    blurb: "Give each restaurant account its own order guide at your prices and SKUs, kept current from one admin platform as stock changes.",
    cluster: 'ops',
  },
  {
    slug: 'restaurant-stock-management-software',
    file: 'vos-restaurant-stock-management-landing.html',
    label: 'Restaurant Stock Management',
    card: 'Restaurant Stock Management Software',
    blurb: "The ordering side of restaurant stock. Check the walk-in, call out the order, and VOS sends it to your distributor.",
    cluster: 'inventory',
  },
  {
    slug: 'restaurant-purchasing-software',
    file: 'vos-restaurant-purchasing-landing.html',
    label: 'Restaurant Purchasing Software',
    card: 'Restaurant Purchasing Software',
    blurb: "Buy from each of your distributors on VOS in one app, by voice, at any hour. Every purchase is on record with its own order number.",
    cluster: 'ops',
  },
  {
    slug: 'vendor-management-software',
    file: 'vos-vendor-management-landing.html',
    label: 'Vendor Management Software',
    card: 'Vendor Management Software',
    blurb: "Be the vendor your restaurant accounts find easiest to buy from: their own order guide, round-the-clock ordering, orders in your format.",
    cluster: 'ops',
  },
  {
    slug: 'restaurant-checklist-software',
    file: 'vos-restaurant-checklist-landing.html',
    label: 'Restaurant Checklist Software',
    card: 'Restaurant Checklist Software',
    blurb: "Your distributor loads your order guide, so ordering runs the same way on every shift. Built for ordering, not a general task app.",
    cluster: 'ops',
  },
];
